language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run test:coverage
  - npm run build
after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=$GnULk1u2ioTQAjZoo7GikSTekmtYwpSQw
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master